"""DOCX ingestion via python-docx (MIT).

Shaped by inspecting a real Thai local-government TOR
(อบต. งานจ้างเหมาบริการธุรการ, 134 paragraphs + 1 table), not by assumption:

1. **Body order has to come from the raw XML.** `document.paragraphs`
   excludes table cell content entirely, and python-docx offers no unified
   document-order view of paragraphs and tables. So the walker iterates
   `document.element.body`'s children, distinguishing `w:p` from `w:tbl`, and
   uses python-docx only to pull text out of each block (which is where it
   earns its keep: line breaks, hyperlinks, field codes, nested runs).

2. **Paragraphs matter more than tables here.** The real sample keeps every
   TOR fact -- objectives, bidder qualifications, deliverables, penalties --
   in hand-numbered paragraphs like "3.3 มีวุฒิการศึกษาไม่ต่ำกว่า...". Tables
   still appear (that sample's one table is a work-measurement grid), so both
   are addressable, but this is the opposite of a spreadsheet where the grid
   is everything.

3. **There are no Word heading styles to lean on.** Every paragraph in the
   real sample uses an autogenerated style (`a7`) or none -- never
   "Heading 1". Section structure is typed into the text by hand. So this
   module does NOT try to derive a heading hierarchy: it would have found
   nothing, and the numbering the model needs is already in the paragraph
   text it reads.

4. **Numerals are mixed.** The sample writes "3๐ รายการ" -- Arabic 3 next to
   Thai ๐, meaning 30 -- and numbers sections as "๔.๑.๑". Every block's text
   goes through `app.thai.normalize.normalize_text`, the same helper the PDF
   path uses, which maps ๐-๙ to 0-9 and applies NFC.

Locators are emitted verbatim in the text as `[para:N]` / `[t1:r2:c3]` so the
model copies the exact string it must put in `Source.ref` -- the same trick
the XLSX path uses with `[B5]`, and the reason `ref`'s format can be
regex-enforced in schema.py.
"""
from __future__ import annotations

import io

from docx import Document
from docx.table import Table
from docx.text.paragraph import Paragraph

from app.ingest.base import IngestedDocument, IngestMeta
from app.models.schema import DocxBlock, SourcePreview
from app.thai.normalize import normalize_text

_W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
_TAG_PARAGRAPH = f"{_W}p"
_TAG_TABLE = f"{_W}tbl"


class DocxTooLargeError(RuntimeError):
    """Raised instead of silently truncating -- a dropped block would make a
    value look absent when it was merely unread (rule #5's spirit)."""


# The real sample has 135 blocks. This leaves room for far longer TORs while
# still refusing a document that would blow the token budget unannounced.
MAX_BLOCKS = 3_000


def ingest_docx_bytes(data: bytes) -> IngestedDocument:
    document = Document(io.BytesIO(data))
    lines: list[str] = []
    blocks: list[DocxBlock] = []
    paragraph_number = 0
    table_number = 0

    for child in document.element.body:
        if child.tag == _TAG_PARAGRAPH:
            text = normalize_text(Paragraph(child, document).text).strip()
            if not text:
                continue  # blank spacer paragraphs carry no citable content
            paragraph_number += 1
            ref = f"para:{paragraph_number}"
            lines.append(f"[{ref}] {text}")
            blocks.append(DocxBlock(ref=ref, text=text, kind="paragraph"))

        elif child.tag == _TAG_TABLE:
            table_number += 1
            for row_index, row in enumerate(Table(child, document).rows, start=1):
                for col_index, cell in enumerate(row.cells, start=1):
                    text = normalize_text(cell.text).strip()
                    if not text:
                        continue
                    ref = f"t{table_number}:r{row_index}:c{col_index}"
                    lines.append(f"[{ref}] {text}")
                    blocks.append(DocxBlock(ref=ref, text=text, kind="table_cell"))

        if len(blocks) > MAX_BLOCKS:
            raise DocxTooLargeError(
                f"ไฟล์ Word นี้มีย่อหน้า/ช่องตารางที่มีข้อความมากกว่า {MAX_BLOCKS:,} รายการ "
                f"ซึ่งเกินขอบเขตที่เครื่องมือนี้อ่านได้ในครั้งเดียว — "
                f"กรุณาแยกเฉพาะส่วนที่เป็น TOR แล้วอัปโหลดใหม่"
            )

    return IngestedDocument(
        document_text="\n".join(lines),
        meta=IngestMeta(
            document_kind="docx",
            paragraph_count=paragraph_number,
        ),
        preview=SourcePreview(document_kind="docx", blocks=blocks),
    )
